from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from backend.app.core.database import Base


class Recommendation(Base):
    """
    ORM model representing an AI-generated recommendation.

    Each recommendation:
    - Belongs to a specific AI risk assessment
    - Contains actionable guidance text
    - May include a category label for grouping or filtering
    - Tracks creation time for auditing and analytics
    """

    __tablename__ = "recommendations"

    # Primary key identifier
    recommendation_id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    # Foreign key linking to the associated AI risk assessment
    # CASCADE ensures recommendations are removed if the parent assessment is deleted
    assessment_id: Mapped[int] = mapped_column(
        ForeignKey("ai_risk_assessments.assessment_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The actual recommendation content generated by the system
    recommendation_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # Optional category label (e.g., "wellbeing", "support", "workload")
    # Can be used for UI grouping or analytics
    category: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    # Timestamp when the recommendation was created
    # Stored with timezone awareness for consistency across environments
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
    )